#ifndef PROJECTWAAAGH_COMPILERDEFS_HPP
#define PROJECTWAAAGH_COMPILERDEFS_HPP

#define PROJECTWAAAGH_PLATFORM_WINDOWS  0
#define PROJECTWAAAGH_PLATFORM_UNIX     1
#define PROJECTWAAAGH_PLATFORM_APPLE    2
#define PROJECTWAAAGH_PLATFORM_INTEL    3

#if defined(_WIN64)
#  define PROJECTWAAAGH_PLATFORM PROJECTWAAAGH_PLATFORM_WINDOWS
#elif defined(__WIN32__) || defined(WIN32) || defined(_WIN32)
#   define PROJECTWAAAGH_PLATFORM PROJECTWAAAGH_PLATFORM_WINDOWS
#elif defined(__APPLE_CC__)
#   define PROJECTWAAAGH_PLATFORM PROJECTWAAAGH_PLATFORM_APPLE
#elif defined(__INTEL_COMPILER)
#   define PROJECTWAAAGH_PLATFORM PROJECTWAAAGH_PLATFORM_INTEL
#else
#   define PROJECTWAAAGH_PLATFORM PROJECTWAAAGH_PLATFORM_UNIX
#endif

#define PROJECTWAAAGH_COMPILER_MICROSOFT    0
#define PROJECTWAAAGH_COMPILER_GNU          1
#define PROJECTWAAAGH_COMPILER_BORLAND      2
#define PROJECTWAAAGH_COMPILER_INTEL        3

#ifdef _MSC_VER
#   define PROJECTWAAAGH_COMPILER PROJECTWAAAGH_COMPILER_MICROSOFT
#elif defined(__BORLANDC__)
#   define PROJECTWAAAGH_COMPILER PROJECTWAAAGH_COMPILER_BORLAND
#elif defined(__INTEL_COMPILER)
#   define PROJECTWAAAGH_COMPILER PROJECTWAAAGH_COMPILER_INTEL
#elif defined(__GNUC__)
#   define PROJECTWAAAGH_COMPILER PROJECTWAAAGH_COMPILER_GNU
#   define GCC_VERSION (__GNUC__ * 10000 + __GNUC_MINOR __ * 100 + __GNUC_PATCHLEVEL__)
#else
#   error "FATAL ERROR: Unknown Compiler."
#endif

#endif //PROJECTWAAAGH_COMPILERDEFS_HPP